CREATE TABLE [dbo].[Cat_Category]
(
	[Cat] VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES [Cat]([Id]) ON DELETE CASCADE ON UPDATE CASCADE, 
    [Category] INT NOT NULL FOREIGN KEY REFERENCES [Category]([Id])
)
